### ISSUE TITLE
Permisssion Problem in v 11.1 for Desktop

### ISSUE THREAD

**Issue by Zeno394** [localsend/localsend#647]
### Discussed in https://github.com/localsend/localsend/discussions/646

<div type='discussions-op-text'>

<sup>Originally posted by **Zeno394** August 30, 2023</sup>
Hi,
First thanks for the new update. I admire that this is the best file transfer software in my knowledge. I am using MX Linux 23 OS.
Problem:
I ve just updated version 1.11 of LocalSend on **Desktop**.
Now when I try to send file and click on **File or Folder button**, I got the error: "NO PERMISSION. You haven't granted necessary permission. Please grant them in Settings."
Now, in Settings, I don't find where to grant the Permission.
And also, I am unable to change "**Download**" directory.  If I click on Download button in Settings, no Response.

Thanks in advance. </div>

**Comment by Tienisto** [comment]
This only occurs on 1.11 but not on 1.10, right? On the Github releases, I published a hotfix (1.11.1) Can you try this out?

**Comment by Zeno394** [comment]
Dear Tien Do Nam,

Thanks for such apk.
The problem was in version 1.10 and 1.11.
But after the file picker in 1.11.1, it runs like butter. Both the sides. Mobile (Pixel 6A, GrapheneOs) <-> Laptop (MX Linux)

Many thanks

**Comment by Zeno394** [comment]
Hi,
Thanks.
Is it possible to add LocalSend in Right Click Context Menu?
So that in file manager, one can right click on a file \ folder and select "send with LocalSend".
Thanks

**Comment by Zeno394** [comment]
Solved

**Comment by rabbiveesh** [comment]
hey, this is still happening to me in the flatpak version on linux, even with the latest 1.14

**Comment by Tienisto** [comment]
Flatpak only has access to the Downloads folder by default. See #256

**Comment by rabbiveesh** [comment]
ah, thanks a bunch @Tienisto !
Maybe the error message should be updated then? it was misleading b/c it told me to change settings, and there was nothing in settings to change

**Comment by Tienisto** [comment]
I don't know if the app can detect if it is in a flatpak environment but it would be certainly better

**Comment by lopugit** [comment]
I'm getting this on both Mac OS Sequoia and iOS 18 👀
